### ISSUE TITLE
How to get gt_depths

### ISSUE THREAD

**Issue by zsz-pro** [hisfog/SfMNeXt-Impl#10]
Nice work!
`gt_path = os.path.join(splits_dir, opt.eval_split, "gt_depths.npz")` in evaluate_depth_config.py corresponds to the path where the ground truth depth data is expected to be for evaluation. It does not directly correspond to the path of the raw data from the KITTI dataset, such as` kitti_data/raw/2011_09_26/2011_09_26_drive_0002_sync/velodyne_points/data/0000000069.bin.`
So how can I get gt_depths.npz?

**Comment by hisfog** [comment]
```python
python export_gt_depth.py --data_path kitti_data --split eigen
python export_gt_depth.py --data_path kitti_data --split eigen_benchmark
```
see https://github.com/nianticlabs/monodepth2#-kitti-evaluation

**Comment by zsz-pro** [comment]
Thanks for your guidance!
