### ISSUE TITLE
The dictionary keys do not match

### ISSUE THREAD

**Issue by zsz-pro** [hisfog/SfMNeXt-Impl#12]
Nice work！
The keys in the encoder_dict do not correspond to the keys in the provided pre-trained weights for KITTI(ResNet50)640*192
![image](https://github.com/hisfog/SfMNeXt-Impl/assets/61933660/26db07f9-8941-4c11-9fbb-b156aaa53540)

**Comment by hisfog** [comment]
Just updated the table in README.md, now the models should load correctly. Additionally, please use the latest code.

**Comment by zsz-pro** [comment]
OK！Thanks!
