### ISSUE TITLE
Difference b/w KITTI and KITTI-with-improved-GT

### ISSUE THREAD

**Issue by surajiitd** [hisfog/SfMNeXt-Impl#17]
Thank you for making your code public ! 
I saw the results in your paper in Table 1 and 2. What is the difference b/w **"KITTI eigen benchmark"** and **"KITTI-with-improved-groundtruth"** ?
What do you call these depths that are on the [official KITTI website](https://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction) , and where can I find the other one?

**Comment by hisfog** [comment]
You can run the `export_gt_depth.py` to get gt_depths of `KITTI eigen benchmark` and `KITTI-with-improved-groundtruth`.
```bash
python export_gt_depth.py --data_path kitti_data --split eigen
python export_gt_depth.py --data_path kitti_data --split eigen_benchmark
```
Depths on the official KITTI website is another test split, neither eigen nor eigen_benchmark, and the gt_depths are not publicly available.
See https://github.com/nianticlabs/monodepth2#-kitti-evaluation

**Comment by surajiitd** [comment]
Thank you @hisfog for clarification!!
