### ISSUE TITLE
The version of kornia

### ISSUE THREAD

**Issue by indu1ge** [hisfog/SfMNeXt-Impl#19]
Thank you  for your code. What's the version of kornia? I cannot install kornia because of the conflict with pytorch.

**Comment by hisfog** [comment]
kornia should be easy to install via `pip`, I think any version should be OK. My kornia version is 0.6.8.
I think you should upgrade your `pip`.

**Comment by indu1ge** [comment]
Thank you for your prompt reply. I successfully installed the environment.
