### ISSUE TITLE
A question about pretrain weights

### ISSUE THREAD

**Issue by Jamesgender** [hisfog/SfMNeXt-Impl#2]
Thanks for your work. My questions is Did you use the vit pretrain weights? In your code it seems that you use the adabins vit pretrain weights.

**Comment by hisfog** [comment]
> Thanks for your work. My questions is Did you use the vit pretrain weights? In your code it seems that you use the adabins vit pretrain weights.

No

**Comment by Jamesgender** [comment]
Thanks for your timely response
