### ISSUE TITLE
Question about the slice of the self-cost volume

### ISSUE THREAD

**Issue by zsz-pro** [hisfog/SfMNeXt-Impl#3]
Thanks for your nice work!
According to the description in section 4.2 Self Query Layer, each slice represents the relative distance between pixels and objects. So why does a bright-dark-bright(near-far-near) situation occur, such as in the image at the second row of the first column?
![image](https://github.com/hisfog/SfMNeXt-Impl/assets/61933660/c9d70d2f-33e6-4e42-8fc9-123ae3ae8db9)

**Comment by zsz-pro** [comment]
Or is the meaning of this "distance" not referring to real-world distance, but rather indicating that the query is more likely to infer the depth of regions with smaller "distance"?

**Comment by hisfog** [comment]
> Thanks for your nice work! According to the description in section 4.2 Self Query Layer, each slice represents the relative distance between pixels and objects. So why does a bright-dark-bright(near-far-near) situation occur, such as in the image at the second row of the first column? ![image](https://user-images.githubusercontent.com/61933660/268597435-c9d70d2f-33e6-4e42-8fc9-123ae3ae8db9.png)

In self-supervised depth setting, we may fail to learn the correct depth of the sky that has no textures. As a result, the sky is always treated as a nearby stationary object. This causes the "near-far-near(sky)" you mentioned.

**Comment by zsz-pro** [comment]
Thanks for your reply! 
So I would like to confirm once again whether "distance" refers to relative distance in the real world.

I have some confusion regarding the step "estimate depth bins b by counting the latent depths in the self-cost volume." My understanding is that the coarse-grained queries may represent objects at different distances. For instance, when query **Qi** corresponds to some distant object **OBJi**, it would yield a relative distance **Vi** (only considering the absolute value of distance, not direction) relative to **OBJi**, as illustrated in the second row of the first column of the image. However, if we do not consider direction, how should we interpret the process of counting the latent depths in the self-cost volume when the query represents an object in the middle of the scene?

**Comment by zsz-pro** [comment]
Thanks for your reply!
I got it!
