### ISSUE TITLE
The smoothloss

### ISSUE THREAD

**Issue by Jamesgender** [hisfog/SfMNeXt-Impl#5]
Hello! My question is about smoothloss.
This version code shows that the output of the model is depth. And you still use 'outputs["disp", 0] = pred' to save the depth you predicted. That is ok. So you changed the behavior in generate_images_pred function.
![image](https://github.com/hisfog/SfMNeXt-Impl/assets/135774928/63b6679f-b301-4413-9962-0ce9d7fc20e4)
But in smoothloss, it seems that you still use depth to compute the smoothloss. Why didnt you use the inverse depth, which means the true disparities for smoothloss as the monodepth2 did? The results will be the same?
![image](https://github.com/hisfog/SfMNeXt-Impl/assets/135774928/1b375008-41fe-4266-bef4-efe55e844fe3)
Thanks!

**Comment by hisfog** [comment]
- Yes, we calculate the smooth loss using depth, and it is feasible. 
- It should also be feasible to calculate the smooth loss using 1 / depth (and it seems more reasonable).
- It seems that there is currently no paper indicating which one is superior. I think we should conduct more experiments to investigate which one is better.

**Comment by Jamesgender** [comment]
OK，thank you for your timely answer！
