### ISSUE TITLE
Only miss FullQueryLayer?

### ISSUE THREAD

**Issue by zsz-pro** [hisfog/SfMNeXt-Impl#6]
Nice work! Is the current code missing only the implementation of the FullQueryLayer class? If so, I can go ahead and fill in that part myself.

**Comment by hisfog** [comment]
Yes. In fact, we believe there is a better implementation for the FullQueryLayer, and we are currently working on it.

**Comment by zsz-pro** [comment]
Thanks for your reply！I also want to make some changes to it. It is really inspiring！



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/21/2023 19:03 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [hisfog/SfMNeXt-Impl] Only miss FullQueryLayer? (Issue #6) |

Yes. In fact, we believe there is a better implementation for the FullQueryLayer, and we are currently working on it.
