### ISSUE TITLE
minor bug:data going out of bounds

### ISSUE THREAD

**Issue by zsz-pro** [hisfog/SfMNeXt-Impl#8]
There is a minor bug. In mono_dataset.py, due to the `frame_idxs` being `[0, -1, 1]`, there can be situations of data going out of bounds when accessing `getitem`.

**Comment by hisfog** [comment]
Yes, if the current frame is the first frame (0th frame) or the last frame of the video clip, there may be situations of out-of-bounds. 
In our experiments, we will discard (not read) the first and last frames to avoid this issue.
